package it.polimi.se2019.model;

public enum ComboType {

    RUNAROUND, GRABSTUFF, SHOOTPEOPLE, FRENZYMOVERELOADSHOOT, FRENZYMOVEFOURSQUARES, FRENZYMOVEGRAB, FRENZYMOVETWICEGRABSHOOT, FRENZYMOVETHRICESHOOT;
}
