package it.polimi.se2019.server.model;

/**
 * This class defines a power up, which is generated by a JSON in PowerUpHelper {@link it.polimi.se2019.server.model.PowerUpHelper}.
 */

public class PowerUp extends Card implements Drawable,Jsonable{
    public PowerUp(String path){
        super(path);
    }

    public PowerUp(PowerUp powerUp){
        super(powerUp);
    }

    public String getColour(){
        String colour="";
        if (name.contains("Red"))
            colour="RED";
        else if (name.contains("Blue"))
            colour="BLUE";
        else if(name.contains("Yellow"))
            colour="YELLOW";
        return colour;
    }
}
